In [1]:
import pandas as pd

In [2]:
happiness = pd.read_excel('..\Datasets\WORLD_HAPPINESS.xls')
happiness

,Country name,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,7.8042,0.036162,7.875078,7.733322,10.792010,0.968770,71.149994,0.961408,-0.018824,0.181745,1.777825,1.888380,1.584900,0.534574,0.771510,0.126331,0.535299,2.363241
1,Denmark,7.5864,0.041028,7.666815,7.505985,10.962164,0.954112,71.250145,0.933533,0.134242,0.195814,1.777825,1.949406,1.547875,0.537302,0.734416,0.208459,0.525221,2.083766
2,Iceland,7.5296,0.048612,7.624879,7.434321,10.895531,0.982533,72.050018,0.936349,0.210987,0.667848,1.777825,1.925508,1.619666,0.559096,0.738164,0.249635,0.187119,2.250382
3,Israel,7.4729,0.031609,7.534853,7.410946,10.638705,0.943344,72.697205,0.808866,-0.023080,0.708094,1.777825,1.833398,1.520674,0.576730,0.568518,0.124048,0.158292,2.691290
4,Netherlands,7.4030,0.029294,7.460416,7.345583,10.942279,0.930499,71.550018,0.886875,0.212686,0.378929,1.777825,1.942274,1.488228,0.545473,0.672327,0.250547,0.394062,2.110044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,Congo (Kinshasa),3.2072,0.095369,3.394124,3.020277,7.006671,0.651610,55.375000,0.663798,0.085998,0.833752,1.777825,0.530779,0.783747,0.104758,0.375472,0.182573,0.068287,1.161580
133,Zimbabwe,3.2035,0.060865,3.322795,3.084205,7.640998,0.689918,54.049889,0.654055,-0.046230,0.765582,1.777825,0.758279,0.880513,0.068653,0.362508,0.111627,0.117115,0.904856
134,Sierra Leone,3.1376,0.082441,3.299184,2.976016,7.394014,0.555251,54.899853,0.660367,0.104929,0.857780,1.777825,0.669699,0.540343,0.091811,0.370907,0.192731,0.051077,1.221006
135,Lebanon,2.3922,0.044495,2.479410,2.304990,9.477677,0.529754,66.148819,0.473900,-0.140915,0.891104,1.777825,1.416999,0.475936,0.398308,0.122771,0.060824,0.027208,-0.109798
136,Afghanistan,1.8590,0.032506,1.922712,1.795288,7.324032,0.341341,54.712410,0.381642,-0.081011,0.847215,1.777825,0.644600,0.000000,0.086704,0.000000,0.092965,0.058644,0.976065

In [3]:
columns_to_drop = list(range(2, 5)) + list(range(happiness.shape[1] - 7, happiness.shape[1]))
happiness = happiness.drop(columns=happiness.columns[columns_to_drop])
happiness

,Country name,Ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia
0,Finland,7.8042,10.792010,0.968770,71.149994,0.961408,-0.018824,0.181745,1.777825
1,Denmark,7.5864,10.962164,0.954112,71.250145,0.933533,0.134242,0.195814,1.777825
2,Iceland,7.5296,10.895531,0.982533,72.050018,0.936349,0.210987,0.667848,1.777825
3,Israel,7.4729,10.638705,0.943344,72.697205,0.808866,-0.023080,0.708094,1.777825
4,Netherlands,7.4030,10.942279,0.930499,71.550018,0.886875,0.212686,0.378929,1.777825
...,...,...,...,...,...,...,...,...,...
132,Congo (Kinshasa),3.2072,7.006671,0.651610,55.375000,0.663798,0.085998,0.833752,1.777825
133,Zimbabwe,3.2035,7.640998,0.689918,54.049889,0.654055,-0.046230,0.765582,1.777825
134,Sierra Leone,3.1376,7.394014,0.555251,54.899853,0.660367,0.104929,0.857780,1.777825
135,Lebanon,2.3922,9.477677,0.529754,66.148819,0.473900,-0.140915,0.891104,1.777825
136,Afghanistan,1.8590,7.324032,0.341341,54.712410,0.381642,-0.081011,0.847215,1.777825

In [4]:
happiness = happiness.rename(columns={'Country name': 'Country'})
happiness

,Country,Ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia
0,Finland,7.8042,10.792010,0.968770,71.149994,0.961408,-0.018824,0.181745,1.777825
1,Denmark,7.5864,10.962164,0.954112,71.250145,0.933533,0.134242,0.195814,1.777825
2,Iceland,7.5296,10.895531,0.982533,72.050018,0.936349,0.210987,0.667848,1.777825
3,Israel,7.4729,10.638705,0.943344,72.697205,0.808866,-0.023080,0.708094,1.777825
4,Netherlands,7.4030,10.942279,0.930499,71.550018,0.886875,0.212686,0.378929,1.777825
...,...,...,...,...,...,...,...,...,...
132,Congo (Kinshasa),3.2072,7.006671,0.651610,55.375000,0.663798,0.085998,0.833752,1.777825
133,Zimbabwe,3.2035,7.640998,0.689918,54.049889,0.654055,-0.046230,0.765582,1.777825
134,Sierra Leone,3.1376,7.394014,0.555251,54.899853,0.660367,0.104929,0.857780,1.777825
135,Lebanon,2.3922,9.477677,0.529754,66.148819,0.473900,-0.140915,0.891104,1.777825
136,Afghanistan,1.8590,7.324032,0.341341,54.712410,0.381642,-0.081011,0.847215,1.777825

In [5]:
happiness.to_csv(r"..\CSV\Hapiness_Index.csv", index=False)

In [6]:
selected_happiness = happiness.loc[happiness['Country'].isin(['Spain', 'Australia'])].copy()
numeric_cols = selected_happiness.columns[1:]
new_row = selected_happiness[numeric_cols].iloc[0] - selected_happiness[numeric_cols].iloc[1]
selected_happiness.loc[selected_happiness.index[-1] + 1] = selected_happiness.iloc[-1].copy()
selected_happiness.loc[selected_happiness.index[-1], numeric_cols] = new_row.values
selected_happiness.loc[32, 'Country'] = 'Difference'
numeric_cols_ = selected_happiness.columns[1:]
new_row_ = (selected_happiness[numeric_cols_].iloc[2] / selected_happiness[numeric_cols_].iloc[1]).round(2)*100
selected_happiness.loc[selected_happiness.index[-1] + 1] = selected_happiness.iloc[-1].copy()
selected_happiness.loc[selected_happiness.index[-1], numeric_cols_] = new_row_.values
selected_happiness.loc[33, 'Country'] = 'Difference in %'
selected_happiness

,Country,Ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia
11,Australia,7.0946,10.821049,0.933870,71.049942,0.890200,0.197561,0.495916,1.777825
31,Spain,6.4362,10.540300,0.931740,72.349976,0.782115,-0.065928,0.710519,1.777825
32,Difference,0.6584,0.280748,0.002131,-1.300034,0.108085,0.263489,-0.214603,0.000000
33,Difference in %,10.0000,3.000000,0.000000,-2.000000,14.000000,-400.000000,-30.000000,0.000000

In [7]:
selected_happiness.to_csv(r"..\CSV\benchmarking_happiness.csv", index=False)